name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pip install poetry==1.7.1
    - name: Install dependencies
      run: |
        poetry install 
    - name: Use Pytest
      run: |
        poetry run pytest
    - name: Use flake8
      run: |
        poetry run flake8
    - name: Use mypy
      run: |
        poetry run mypy nest

